### ISSUE TITLE
Moving Towards Version 3

### ISSUE THREAD

**Issue by oscartbeaumont** [oscartbeaumont/ElectronPlayer#90]
As many of you have may or may not have noticed, this project has been sitting unmaintained for the last while. This has been due to the issues I have faced with supporting Widevine which is the DRM required to make the streaming services function. I was unable to get the proper certification so that the application was able to handle the Widevine Verified Media Platform (VMP) which is required for Widevine media playback on Windows on macOS. I did not have the free time to put into a project that was going to stop working the second the large streaming services stop supporting the old version of the Chromium the app is built on which is due to these Widevine issues.

I have recently been made aware on [Castlabs Electron EVS](https://github.com/castlabs/electron-releases/wiki/EVS) service which seems to allow me to fix these Widevine issues. As the codebase is old, messy and does not reflect modern standards, a rebuild from the ground up is in order. Below is tracking this progress.

Castlabs Electron EVS Validation Process:
 - [x] Electron + Widevine building for Windows (msi)
 - [ ] Electron + Widevine building for macOS (app)
 - [x] Electron + Widevine building for Linux (snap, appimage)

Features:
 - [ ] Local Configuration - Move from `electron-store` so errors in configuration can be handled better (#61) and also handle file permissions (#72)
 - [ ] Translation's Framework - Allows all strings to be replaced from English. Include translations from [fork here](https://github.com/ToMattBan/ElectronPlayer/tree/v2.0.9)
 - [ ] Sign in to Google accounts - Use Generic Chrome User-Agent (#89, #40)
 - [ ] GUI Service Management - Also Clean Default Services and Add services from my email
 - [ ] Launch service from terminal (#79)
 - [ ] Browser Navigations - Back, Forward, Go to URL, Reload, Bookmarks?
 - [ ] Testable Codebase
 - [ ] GitHub Actions - CI/CD
 - [ ] Fix Analytics Framework
 - [ ] Prompt Users to Donate

Thank you to everyone who is using the application and I hope if everything goes smooth with this rewrite the application will be on a new level of both maintainability and features.

**Comment by sronweb** [comment]
I'm with Ubuntu 21.04, and as I see I can install only v.2.0.7 and 2.0.8. I hope to test v.3.0.0 as soon I can.

**Comment by fir3-1ce** [comment]
Is Twitch any easier to maintain? It's the only service I use on Ubuntu, and it would be great to get a standalone app for it. I just wish it had picture in picture and the ability to pop out the chat like in Firefox. Cool project nonetheless
